name: create PR
on:
  workflow_dispatch:
jobs:
  create_pr:
    uses: bahag-banasiks/github-actions-create-auto-pull-request/.github/workflows/actions.yaml@main
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      title: "Create PR"
      body: "Create PR"
      head: "test997"
      base: "main"
      repository: $GITHUB_REPOSITORY
      labels: "bug"